drop table if exists folders;
drop table if exists notes;

create table folders (
  id integer primary key generated by default as identity,
  name text not null unique
);

create table notes (
  id integer primary key generated by default as identity,
  name text not null,
  date_modified timestamptz not null default now(),
  description text,
  folder integer references folders(id)
);